package models

import "time"

// SystemAlert represents an alert generated by the analysis agent.
type SystemAlert struct {
	ID         string    `json:"id" db:"id"`
	Severity   string    `json:"severity" db:"severity"`
	Message    string    `json:"message" db:"message"`
	IsResolved bool      `json:"is_resolved" db:"is_resolved"`
	CreatedAt  time.Time `json:"created_at" db:"created_at"`
}
