FROM node:20-alpine AS builder
WORKDIR /app
COPY ../webui/package*.json ./
RUN npm ci
COPY ../webui .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
